#!/bin/sh
# chasquid entrypoint (platform-managed): generates the configuration
# (spec §60), supervises the MTA (restarting it on exit — e.g. after the
# sidecar requests a restart for new-domain registration, §91), then runs
# the sidecar in the foreground.
set -e

hostname="${CHASQUID_HOSTNAME:-mail.local}"

render_config() {
  cat > /etc/chasquid/chasquid.conf <<EOF
# Generated by the selfu platform (spec §60, §90). Do not edit by hand.
hostname: "$hostname"
data_dir: "/data"
smtp_address: "0.0.0.0:25"
submission_address: "0.0.0.0:587"
mail_delivery_agent_bin: "/usr/local/bin/mda.sh"
mail_delivery_agent_args: ["-f", "%from%", "-d", "%to_user%"]
monitoring_address: ""
mail_log_path: "<stdout>"
EOF
}

mkdir -p /etc/chasquid/certs /etc/chasquid/domains /data/spool
# Development TLS: a self-signed pair per hostname (certbot layout,
# spec §52). Production replaces this via real certificates.
cdir="/etc/chasquid/certs/$hostname"
if [ ! -f "$cdir/fullchain.pem" ] && command -v openssl >/dev/null 2>&1; then
  mkdir -p "$cdir"
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -keyout "$cdir/privkey.pem" \
    -out "$cdir/fullchain.pem" \
    -subj "/CN=$hostname" >/dev/null 2>&1
fi
# chasquid v1.17 exits if domains/ is empty. Seed a placeholder local
# domain (the MTA hostname, no users); real domains are provisioned by the
# platform alongside it.
if [ -z "$(ls -A /etc/chasquid/domains 2>/dev/null)" ]; then
  mkdir -p "/etc/chasquid/domains/$hostname"
  touch "/etc/chasquid/domains/$hostname/users" "/etc/chasquid/domains/$hostname/aliases"
fi
render_config

# Supervisor loop: keep chasquid running; restart whenever it exits.
(
  while true; do
    /usr/local/bin/chasquid -config_dir /etc/chasquid &
    wait "$!"
    sleep 2
  done
) &

exec /usr/local/bin/chasquid-agent